[[key]]
name = "name 1"
secret = "JBSWY3DPEHPK3PXP"

[[key]]
name = "name 2"
secret = "JBSWY3DPEHPK3PXP"

[[key]]
name = "name 3"
secret = "JBSWY3DPEHPK3PXP"

[[key]]
name = "name 4"
secret = "JBSWY3DPEHPK3PXP"